apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-tcc-prd
spec:
  acme:
    email: magaiver.santos@universo.univates.br
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: tcc-issuer-key
    solvers:
    - http01:
        ingress: 
          class: haproxy
