  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: jupyter-ingress
    namespace: spark
    annotations:
      ingress.class: "haproxy"
      ingress.kubernetes.io/rewrite-target: /
      cert-manager.io/cluster-issuer: letsencrypt-tcc-staging
  spec:
    rules:
    - host: jupyter.magaiver.dev
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: jupyter-labs-ui
              port:
                number: 8888


    tls:
    - hosts:
      - "jupyter.magaiver.dev"
      secretName: "jupyter-conversao-tls-staging"

