  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: console-ingress
    annotations:
      ingress.class: "haproxy"
      cert-manager.io/cluster-issuer: letsencrypt-tcc-prd
  spec:
    rules:
    - host: console.magaiver.dev
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
               name: console
               port: 
                 number: 9443

    tls:
    - hosts:
      - "console.magaiver.dev"
      secretName: "console-conversao-tls"

  
