apiVersion: v1
kind: Service
metadata:
  name: minio-api-svc
  namespace: minio-tenant
spec:
  type: NodePort
  ports:
   - protocol: TCP
     port: 9000
     nodePort: 30900
  selector:
    v1.min.io/tenant: minio
